=== abhinavs03/wsdlab5/onlinemovieticketing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           elementFormDefault="qualified" 
           attributeFormDefault="unqualified" 
           targetNamespace="http://www.example.com/onlinemovieticketing" 
           xmlns:movie="http://www.example.com/onlinemovieticketing">

    <!-- Define the root element -->
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="showtime" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="availableSeats" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== abhinavs03/wsdlab5/onlinemovieticketing.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="onlinemovieticketing.xsl" type="text/xsl" ?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/onlinemovieticketing" xsi:schemaLocation="http://www.example.com/onlinemovieticketing onlinemovieticketing.xsd">
    <movie>
        <title>Inception</title>
        <showtime>2024-08-11T19:00:00</showtime>
        <price>12.50</price>
        <availableSeats>120</availableSeats>
    </movie>
    <movie>
        <title>The Matrix</title>
        <showtime>2024-08-11T21:00:00</showtime>
        <price>10.00</price>
        <availableSeats>150</availableSeats>
    </movie>
</movies>
